<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [52]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure

# creating two empty list 'A' and 'B'
A = []
B = []

# making matrix with user input and the function will return list of list
def create_matrix(matrix):
  # number rows and column as input
  R = int(input("Enter number of rows : "))
  C = int(input("Enter number of columns : "))
  # iterating till the range
  for i in range(R):
    element=[]
    print("enter {} values for matrix row {}".format(C,i+1))
    for j in range(C):
      element.append(eval(input())) # putting each value in a row(element[] list) one by one
    matrix.append(element)          #putting each element[] list in matrix one by one
  return matrix


"""  len(B) ==> gives number of row in matrix B
     len(A[0]) ==> gives number of column in matrix A   """

# here A and B are list of lists
def matrix_mul(A, B):
  # write your code
  mul_res=[]
  #putting all 0 value in result matrix
  # a(mxn)*b(nxs) = res(mxs)  means, if a is mxn matrix, b-->nxs then res will be of mxs
  # and multiplication is only possible if col of a should == to row of matrix b
  for i in range(len(A)):  # no of row of result matrix=row of A=len(A)
    mul_res.append([0]*len(B[0])) # no of column of result matrix=col of B=len(B[0])
  #print(result)
  for row_A in range(len(A)):     # iterating by row of A
    for col_B in range(len(B[0])):  # iterating by column by B
      for row_B in range(len(B)):     # iterating by rows of B
        mul_res[row_A][col_B] += A[row_A][row_B] * B[row_B][col_B]
  return(mul_res)


#calling create_matrix() fun to make matrix(list of list)
create_matrix(A)
print("matrix A is {}\n".format(A))
create_matrix(B)
print("matrix B is {}\n".format(B))

if(len(A[0]) == len(B)):
  multiplication_result=matrix_mul(A, B)
  print("multiplication of matrix {} and {}  is \n {}".format(A,B,multiplication_result))
else:
  print("multiplication is not possible")


Enter number of rows : 3
Enter number of columns : 3
enter 3 values for matrix row 1
1
3
4
enter 3 values for matrix row 2
2
5
7
enter 3 values for matrix row 3
5
9
6
matrix A is [[1, 3, 4], [2, 5, 7], [5, 9, 6]]

Enter number of rows : 3
Enter number of columns : 3
enter 3 values for matrix row 1
1
0
0
enter 3 values for matrix row 2
0
1
0
enter 3 values for matrix row 3
0
0
1
matrix B is [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

multiplication of matrix [[1, 3, 4], [2, 5, 7], [5, 9, 6]] and [[1, 0, 0], [0, 1, 0], [0, 0, 1]]  is 
 [[1, 3, 4], [2, 5, 7], [5, 9, 6]]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [36]:
from random import uniform
import numpy
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure

#create the list A by user
A = [eval(value) for value in input("Enter the list values followed by space: ").split()]
print("list A is {} \n".format(A))

def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude

    #finding sum of list
    list_sum=0
    for num in A:
      list_sum += num
    #print("sum of list values is {}\n".format(list_sum))

    #normalize using sum
    norm_sum=[]
    for num in A:
      norm_sum.append(num/list_sum)
    #print("norm sum of list_sum {} is {}\n".format(list_sum,norm_sum))

    #calculate cumulative sum
    cum_sum = []
    cum_norm_val=0
    for norm_val in norm_sum:
      cum_norm_val += norm_val
      cum_sum.append(cum_norm_val)
    #print("cumulative sum of norm_sum {} is {}\n".format(norm_sum,cum_sum))

    #sample one value using uniform r.v with range(0.0,1.0)
    sampled_1_uniform_val = numpy.random.uniform(0.0,1.0,1)

    #proportional sample
    for (norm_value, cum_sum_value) in zip(norm_sum, cum_sum):
      if(sampled_1_uniform_val <= cum_sum_value):
        return norm_value;


def sampling_based_on_magnitued():
    for i in range(1,100): #100
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

Enter the list values followed by space: 1 5 9 15 88 11 12
list A is [1, 5, 9, 15, 88, 11, 12] 

0.624113475177305
0.0851063829787234
0.624113475177305
0.10638297872340426
0.624113475177305
0.624113475177305
0.624113475177305
0.624113475177305
0.624113475177305
0.624113475177305
0.10638297872340426
0.624113475177305
0.624113475177305
0.624113475177305
0.0851063829787234
0.06382978723404255
0.07801418439716312
0.624113475177305
0.624113475177305
0.10638297872340426
0.624113475177305
0.07801418439716312
0.624113475177305
0.624113475177305
0.624113475177305
0.624113475177305
0.624113475177305
0.624113475177305
0.07801418439716312
0.07801418439716312
0.624113475177305
0.624113475177305
0.0851063829787234
0.624113475177305
0.07801418439716312
0.624113475177305
0.624113475177305
0.0851063829787234
0.10638297872340426
0.10638297872340426
0.07801418439716312
0.624113475177305
0.10638297872340426
0.0851063829787234
0.06382978723404255
0.624113475177305
0.624113475177305
0.624113475177305
0.6241

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [37]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
given_string = input("Enter the string:: ")
def replace_digits(String):
    # write your code
    replacable_characters = r'[^0-9]'

    # Match all digits in the string and replace them with an empty string
    modified_string = re.sub(replacable_characters, '', given_string)
    print("modified string is:: {}".format(modified_string))
    length = len(modified_string)
    print("\noutput string is")
    return(modified_string.replace(modified_string,'#'*length))

replace_digits(given_string)

################# Method2 ########################
# given_string = input("Enter the string:: ")
# def replace_digits(String):
#     # write your code
#     replacable_characters = r'[0-9]'
#     result = ""

#     # Match all digits in the string and replace them with an empty string
#     modified_string = re.sub(replacable_characters, '', given_string)
#     length = len(given_string) - len(modified_string)
#     return(result.join('#'*length))

# replace_digits(given_string)

Enter the string:: #2a$#b%c%561#
modified string is:: 2561

output string is


'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a.
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
#userInput1  students==>  'student1' 'student2' 'student3' 'student4' 'student5' 'student6' 'student7' 'student8' 'student9' 'student10'
#userInput  marks ==>     45 78 12 14 48 43 47 98 22 80

students = [value for value in input("Enter the students name followed by space:: ").split()]
marks    = [int(value) for value in input("Enter the corresponding marks of students followed by space:: ").split()]


def top5students(dictionary):
  #sort in descending order of values
  list_dictionary = sorted(dictionary.items(), key=lambda val:val[1], reverse=True)   #return list
  N=5
  # Get first N items in dictionary
  result = dict(list_dictionary[0:N])
  return result

def least5students(dictionary):
  #sort in ascending order of values
  list_dictionary = sorted(dictionary.items(), key=lambda val:val[1], reverse=False) # it return a list
  N=5
  # Get first N items in dictionary
  result = dict(list_dictionary[0:N])
  return result

def studentsBW25and75(dictionary,max_mark,min_mark,per_25,per_75):
  diff_bw_maxmin_marks = max_mark - min_mark
  Cal_25_percentile = diff_bw_maxmin_marks*(per_25/100)
  Cal_75_percentile = diff_bw_maxmin_marks*(per_75/100)
  dictionary= dict(sorted(dictionary.items(), key=lambda val:val[1], reverse=False))

  result = {
      student_name : student_mark
      for (student_name,student_mark) in dictionary.items()
            if(Cal_25_percentile <= student_mark <= Cal_75_percentile)
  }
  return result

def display_dash_board(students, marks):
    #convert students,marks in dictionary as key value pair whare keys==>students, values==>marks
    dict_data = dict(zip(students,marks))
    # write code for computing top top 5 students
    top_5_students = top5students(dict_data)# compute this
    # write code for computing top least 5 students
    least_5_students = least5students(dict_data)# compute this
    # write code for computing 5 students whose mark is in the range [25,75] percentile
    maxStudentMark = max(marks)
    minStudentMark = min(marks)
    per_25 = 25
    per_75 = 75
    students_within_25_and_75 = studentsBW25and75(dict_data,maxStudentMark,minStudentMark,per_25,per_75)

    return top_5_students, least_5_students, students_within_25_and_75

def print_students_details(student_type,dictionary):format(i)
  print("\n{} students::".format(student_type))
  for (key,value) in dictionary.items():
    print("{} \t {}".format(key,value))



def print_table_view(top_5_students, least_5_students, students_within_25_and_75):
  print_students_details("Top 5",top_5_students)
  print_students_details("Least 5",least_5_students)
  print_students_details("obtained mark between 25 and 75 percentile",students_within_25_and_75)

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print_table_view(top_5_students, least_5_students, students_within_25_and_75)

Enter the students name followed by space:: 'student1' 'student2' 'student3' 'student4' 'student5' 'student6' 'student7' 'student8' 'student9' 'student10'
Enter the corresponding marks of students followed by space:: 45 78 12 14 48 43 47 98 22 80

Top 5 students::
'student8' 	 98
'student10' 	 80
'student2' 	 78
'student5' 	 48
'student7' 	 47

Least 5 students::
'student3' 	 12
'student4' 	 14
'student9' 	 22
'student6' 	 43
'student1' 	 45

obtained mark between 25 and 75 percentile students::
'student9' 	 22
'student6' 	 43
'student1' 	 45
'student7' 	 47
'student5' 	 48


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure

# creating empty list S
S = []
print_N_ord = 5

# making matrix with user input and the function will return list of list
def create_listof_coordinates(coordinate_list):
  # number rows and column as input
  co_ord = int(input("Enter number of co-ordinates : "))
  axis = int(input("Enter number of axis(if x,y==>put 2, (x,y,z)==>3 if n-D put n : "))
  # iterating till the range
  for i in range(co_ord):
    element=[]
    print("enter {} values for  co-ordinate{} followed by space".format(axis,i+1))
    element=[int(value) for value in input().split()] # putting each value in a row(element[] list) one by one
    coordinate_list.append(element)          #putting each element[] list in matrix one by one
  return coordinate_list

def point_distance(co_ordinate,P):
  numerator = co_ordinate[0]*P[0]+co_ordinate[1]*P[1]
  denomenator = (math.sqrt(co_ordinate[0]**2 + co_ordinate[1]**2)) * (math.sqrt(P[0]**2 + P[1]**2))
  value=math.acos(numerator/denomenator)
  return value


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    dict_of_closest_points_to_p={}
    list_of_closest_points_to_p=[]
    for co_ordinate in S:
        dict_of_closest_points_to_p[co_ordinate]=point_distance(co_ordinate,P)
    # list_of_closest_points_to_p.append(k[0])
    [list_of_closest_points_to_p.append(k) for k in
     list(dict(sorted(dict_of_closest_points_to_p.items(), key=lambda val:val[1], reverse=False)))[0:print_N_ord]]  #sort in ascending order

    return list_of_closest_points_to_p  # its list of tuples

create_listof_coordinates(S)
S = [tuple(sub) for sub in S]
print("list of tuple S={}".format(S))
#S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

# #TEST point_distance(co_ordinate,P) fun
# co_ordinate= (6,-7)
# P= (3,-4)
# points = point_distance(co_ordinate,P)
#o/p==>0.06512516333438509


points = closest_points_to_p(S, P)
print("{} closest points from {} are".format(print_N_ord,P))
print(*points,sep="\n") #print the returned values
#S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]

Enter number of co-ordinates : 9
Enter number of axis(if x,y==>put 2, (x,y,z)==>3 if n-D put n : 2
enter 2 values for  co-ordinate1 followed by space
1 2
enter 2 values for  co-ordinate2 followed by space
3 4
enter 2 values for  co-ordinate3 followed by space
-1 1
enter 2 values for  co-ordinate4 followed by space
6 -7
enter 2 values for  co-ordinate5 followed by space
0 6
enter 2 values for  co-ordinate6 followed by space
-5 -8
enter 2 values for  co-ordinate7 followed by space
-1 -1
enter 2 values for  co-ordinate8 followed by space
6 0
enter 2 values for  co-ordinate9 followed by space
1 -1
list of tuple S=[(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
5 closest points from (3, -4) are
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [47]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
"""
distance(perpendicular distance) of a point P(x1,y1) from a line:"Ax+By+C=0" is
d=(Ax1+By1+C)/(sqrt(A*A+B*B))

if(distace of all red points from the given line is +ve && distace of all blue points from the given line is -ve)
    "line seperates the blue and red points"
else
    "line does not seperate the blue and red points"

"""
import re

def calculate_ABC(line):
    list_of_ABC_coefficient = [float(co_efficient) for co_efficient in re.split('[xy]', line)]
    return list_of_ABC_coefficient[0],list_of_ABC_coefficient[1],list_of_ABC_coefficient[2]

def calculate_distance(coord,A,B,C):
    return (A*coord[0]+B*coord[1]+C)/(math.sqrt(A**2+B**2))

# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    #calculate A,B,C from the line equation
    A,B,C = calculate_ABC(line)

    for red_coord in red:
      red_dist=calculate_distance(red_coord,A,B,C)
      if(red_dist > 0):
        pass
      else:
        return "NO"

    for blue_coord in blue:
      blue_dist=calculate_distance(blue_coord,A,B,C)
      if(blue_dist < 0):
        pass
      else:
        return "NO"
    return "YES"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]


print("Output::")
for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print("is Line %s seprates red and blue points?"%i, end = ' ')
    print(yes_or_no) # the returned value

Output::
is Line 1x+1y+0 seprates red and blue points? YES
is Line 1x-1y+0 seprates red and blue points? NO
is Line 1x+0y-3 seprates red and blue points? NO
is Line 0x+1y-0.5 seprates red and blue points? YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _)
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex:
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



<h2>How do I think about the solution of this problem</h2>


In [31]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(str):
    # your code
    resultant_str = str.split(',')
    #print(resultant_str)
    result = []#smoothed_values

    length = len(resultant_str)

    division_flag = 0
    cum_sum_of_pre_and_next_value = 0
    appendable_value_in_result = 0
    for index in range(length):
      division_flag += 1

      cum_sum_of_pre_and_next_value += int(resultant_str[index]) if(resultant_str[index] != '_') else 0

      if(index != 0 and resultant_str[index] != '_'):
        appendable_value_in_result = cum_sum_of_pre_and_next_value // division_flag
        while(division_flag != 1):
          result.append(appendable_value_in_result)
          division_flag -= 1
          cum_sum_of_pre_and_next_value = appendable_value_in_result

      """
      dry run purpose::
      print("iteration{}: \n cum_sum = {}, division_flag = {}, appendable_value = {}, \n result = {}\n".format(index+1, cum_sum_of_pre_and_next_value, division_flag, appendable_value_in_result, result))
      """

    if(division_flag != 0):
      appendable_value_in_result = cum_sum_of_pre_and_next_value // division_flag
      while(division_flag != 0):
        result.append(appendable_value_in_result)
        division_flag -= 1
    else:
      result.append(appendable_value_in_result)

    """
    dry run purpose::
    print("iteration{}: \n cum_sum = {}, division_flag = {}, appendable_value = {}, \n result = {}\n".format(index+1, cum_sum_of_pre_and_next_value, division_flag, appendable_value_in_result, result))
    """
    return result#list of values

S=  "_,_,30,_,_,_,50,_,_"
# S=  "_,_,_,24"
# S=  "40,_,_,_,60"
# S=  "80,_,_,_,_"
smoothed_values= curve_smoothing(S)
print("result = %s"%smoothed_values)# print above values

result = [10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [48]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code

"""
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
Logic::
conditional probability, P(F|S)=P(F intersection S)/ P(S)
a) P(F intersection S) ==> (F & S both value comes in a single list [F,S]) / (total no of list in list of list)
 exm:- P(F1 intersection S1) = (no of(['F1','S1']) in list of list A)/ (len(A)) = 1/10

b) P(S) = (no of S in list [F,S])/ (total no of list in list of list)
  exm:- P(S1)= (total no of 'S1' in list [F,S])/len(A) = 4/10

EXM:-
    P(F1|S1)=P(F1 intersection S1)/ P(S1)
            =(1/10)/(4/10)=1/4 Ans

direct method::
  P(F=f|S=s) = (no of ['f','s'] in list of list A) / (no of list [F,S] that is having 's' )
  exm:-
    P(F=F1|S=S1) = (no of ['F1','S1'] in list of list A) / (no of list [F,S] that is having 'S1' )
                 = 1/4

    explian==> in A there is 1 ['F1','S1'] and 4 list are there in A which is having 'S1'
               that are, ['F1','S1'],['F2','S1'],['F4','S1'],['F5','S1']

"""
i=97 #unicode code of 'a'
j=1
def print_formatted_output(f,s,fs_count,s_count):
    global i
    global j
    print("{}) P(F={}|S=={})={}/{}".format(chr(i),f,s,fs_count,s_count),end="  \t")
    if(j==3):
      print()#new line
      j=0
    i += 1
    j += 1

def conditional_probabilites(A,F,S):
    F_S_count = 0
    F_S_new_list = []
    for val in A:
        if(val[1] == S):
            F_S_new_list.append(val)
    S_count = len(F_S_new_list)
    # print(F_S_new_list)
    for FS_val in F_S_new_list:
          if(FS_val[0] == F and FS_val[1] == S):
              F_S_count += 1

    print_formatted_output(F,S,F_S_count,S_count)




# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    #making all combination of F,S for putting the F,S in function "conditional_probabilites()""
    all_comb_FS=[['F1','S1'],['F1','S2'],['F1','S3'],
                 ['F2','S1'],['F2','S2'],['F2','S3'],
                 ['F3','S1'],['F3','S2'],['F3','S3'],
                 ['F4','S1'],['F4','S2'],['F4','S3'],
                 ['F5','S1'],['F5','S2'],['F5','S3'],]
    for fs_arg in all_comb_FS:
        conditional_probabilites(A,fs_arg[0],fs_arg[1])
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

a) P(F=F1|S==S1)=1/4  	b) P(F=F1|S==S2)=1/3  	c) P(F=F1|S==S3)=0/3  	
d) P(F=F2|S==S1)=1/4  	e) P(F=F2|S==S2)=1/3  	f) P(F=F2|S==S3)=1/3  	
g) P(F=F3|S==S1)=0/4  	h) P(F=F3|S==S2)=1/3  	i) P(F=F3|S==S3)=1/3  	
j) P(F=F4|S==S1)=1/4  	k) P(F=F4|S==S2)=0/3  	l) P(F=F4|S==S3)=1/3  	
m) P(F=F5|S==S1)=1/4  	n) P(F=F5|S==S2)=0/3  	o) P(F=F5|S==S3)=0/3  	


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex:
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    s1_list = S1.split(" ")
    s2_list = S2.split(" ")
    a = len(list(set(s1_list) & set(s2_list)))
    b = list(set(s1_list) - set(s2_list))
    c = list(set(s2_list) - set(s1_list))

    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print("a. {}\nb. {}\nc. {}".format(a,b,c))

a. 7
b. ['F', 'first', '5']
c. ['3', 'second', 'S']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [21]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    loss=0
    for Y in A:
      loss += (-1/len(A)) * (Y[0]*math.log10(Y[1]) + (1-Y[0])*math.log10(1-Y[1]) )

    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print("%0.7f"%loss)

0.4243099
